language: go
go:
  - 1.1.2
  - 1.2
  - tip
env:
  - GOARCH=amd64
install:
  - go get github.com/gorilla/mux
  - go get github.com/lib/pq
  - go get github.com/eaigner/hood
notifications:
  email: false
